### ISSUE TITLE
A question about the parameters

### ISSUE THREAD

**Issue by November666** [carrierlxk/COSNet#15]
Hi， thanks for your code，but i am wonder for the parameters ：all_channel and all_dim indicate in the class CoattentionModel，and how to config it，thank you
class CoattentionModel(nn.Module):
    def  __init__(self, block, layers, num_classes, all_channel=256, all_dim=32*32):	#473./8=60

**Comment by carrierlxk** [comment]
Hi, for channel number, you can choose 256 or 512 empirically. For dim, it is decided by input image size, dim = ceil( im_size / 8). I have changed the related code in the model file, so these two parameters have no effect on the experiment setting.

**Comment by November666** [comment]
thank you for reply，can i think that the channel number is irrelevant with the inputimage？

**Comment by carrierlxk** [comment]
yes
