### ISSUE TITLE
Couldn't get the same result in paper when test with your pretrained weight and crf used.

### ISSUE THREAD

**Issue by crazyblacker** [carrierlxk/COSNet#22]
J_mean=77.5% on DAVIS16 when I use reference frame=2 with crf used, and receive same reult when reference frame=5. Why?

**Comment by carrierlxk** [comment]
Hi, I do not know your settings. You can obtain 78.3% of mean J when you run the test code directly. You can obtain 80.5 after CRF optimization. When reference number increase from 2 to 5, the mean J increases to 79.0%.
