### ISSUE TITLE
test setting

### ISSUE THREAD

**Issue by looong96** [carrierlxk/COSNet#23]
1.保持代码原有设置参数不变，即sample-range=2和without crf，由于输出非二值，故对output1取阈值0.5，此时测试指标为78.1（使用davis16官方指标计算代码）。另取sample-range=5，精度依然78.1。为何，求教？
2.您公布的测试mask中，davis16的结果中概率图和二值图混杂，为何，求教？

**Comment by carrierlxk** [comment]
1. The performance difference comes from the fusion, current version is based on  prediction level fusion for simplication, so the performance gain is slight (but it has) when reference image num changes from 2 to 5. For the feature level fusion, you need revise the model and test the related model. 
2.  I will check the results.  You can also download the results of COSNet from davis benchmark (https://davischallenge.org/davis2016/soa_compare.html).
