### ISSUE TITLE
测试路径问题

### ISSUE THREAD

**Issue by taxuewuhenxiaoer** [carrierlxk/COSNet#25]
为什么一直有这个问题
 File "test_coattention_conf.py", line 296, in <module>
    main()
  File "test_coattention_conf.py", line 170, in main
    db_test = db.PairwiseImg(train=False, inputRes=(473,473), db_root_dir=args.data_dir,  transform=None, seq_name = None, sample_range = args.sample_range) #db_root_dir() --> '/path/to/DAVIS-2016' train path
  File "/home/xiaow/code/videosaliency/COSNet-master/dataloaders/PairwiseImg_test.py", line 82, in __init__
    images = np.sort(os.listdir(os.path.join(db_root_dir , 'JPEGImages/480p/',  seq.strip('\n'))))
FileNotFoundError: [Errno 2] No such file or directory: '/JPEGImages/480p/blackswan/00000.jpg /Annotations/480p/blackswan/00000.png '
求解

**Comment by carrierlxk** [comment]
Hi, change the 'db_root_dir' to your own folder path that contains DAVIS-2016 dataset.

**Comment by taxuewuhenxiaoer** [comment]
把这个路径修改了，但还是报路径错误FileNotFoundError: [Errno 2] No such file or directory: '/JPEGImages/480p/blackswan/00000.jpg /Annotations/480p/blackswan/00000.png '而且在这一行为什么会报annotation这边的路径错误呢

**Comment by taxuewuhenxiaoer** [comment]
好的，问题解决，非常感谢
