### ISSUE TITLE
请问train_aug.txt这个文件夹里是什么？和训练数据集问题？

### ISSUE THREAD

**Issue by taxuewuhenxiaoer** [carrierlxk/COSNet#26]
1）args.data_list = './dataset/list/VOC2012/train_aug.txt' 请问train_aug.txt这个文件夹里是什么？
2）想问下您训练的时候都用的哪些数据集呀？davis, voc2012, cityscapes都用了？还有就是cityscapes是哪个数据集呀？请问能提供下载地址吗？您在训练的时候写得Download all the training datasets, including MARA10K and DUT saliency datasets. Create a folder called images and put these two datasets into the folder，训练是用的MARA10K and DUT saliency datasets这两个数据集？

**Comment by carrierlxk** [comment]
Hi,
args.data_list  is useless.  We use MARA10K and DUT saliency datasets for network training.

**Comment by taxuewuhenxiaoer** [comment]
非常感谢解答
还有在PairwiseImg_video.py代码里：
with open('/home/ubuntu/xiankai/saliency_data.txt') as f，请问saliency_data.txt里面是什么呢？

**Comment by carrierlxk** [comment]
The dataset names of MAR10K and DUTs.

**Comment by taxuewuhenxiaoer** [comment]
好的，非常感谢
