### ISSUE TITLE
AttributeError: 'CoattentionModel' object has no attribute 'main_classifier'

### ISSUE THREAD

**Issue by taxuewuhenxiaoer** [carrierlxk/COSNet#28]
运行train_iteration_conf.py的时候，出现错误AttributeError: 'CoattentionModel' object has no attribute 'main_classifier'？？请问这个怎么解决的？

**Comment by carrierlxk** [comment]
'main_classifier' belongs to the backbone of resent. Pls check the related name.

**Comment by NoaHimesaka** [comment]
> 运行train_iteration_conf.py的时候，出现错误AttributeError: 'CoattentionModel' object has no attribute 'main_classifier'？？请问这个怎么解决的？

请问你后来是怎么解决的呀？

**Comment by taxuewuhenxiaoer** [comment]
不好意思，我忘了怎么解决的，你看看，是哪行代码出问题了？

**Comment by Lanezzz** [comment]
> 
> 
> > 运行train_iteration_conf.py的时候，出现错误AttributeError: 'CoattentionModel' object has no attribute 'main_classifier'？？请问这个怎么解决的？
> 
> 请问你后来是怎么解决的呀？

您好，我最近也是在训COSnet，能请教一些问题吗？我只对比过显著性检测的指标，已经能达到差不多的结果了，唯一好奇的就是我的损失函数，60个epoch之后，损失还是在0.4左右，感觉不太正常啊。。。

**Comment by Lanezzz** [comment]
> 
> 
> > 运行train_iteration_conf.py的时候，出现错误AttributeError: 'CoattentionModel' object has no attribute 'main_classifier'？？请问这个怎么解决的？
> 
> 请问你后来是怎么解决的呀？

能加个好友交流一下吗。qq1164481749

**Comment by Lanezzz** [comment]
@NoaHimesaka

**Comment by Lanezzz** [comment]
@NoaHimesaka  能加个好友交流一下吗？1164481749
