### ISSUE TITLE
Error after filling a val_seqs.txt

### ISSUE THREAD

**Issue by Arnhav-Datar** [carrierlxk/COSNet#29]
Hi,

I recently saw your work and was  impressed by it. I want to run this code on my system.  I came across an error and kindly request your help/guidance in resolving it.
I followed the instructions given in the repository very carefully upon which it gave me the error:- \
**FileNotFoundError: [Errno 2] No such file or directory: './DAVIS/val_seqs.txt'**

Upon this I created a file ./DAVIS/val_seqs.txt in which I added the following address
_/home/ubuntu/COSNet/DAVIS/JPEGImages/480p/bear/_

After doing this, I encountered the following error:-
**Traceback (most recent call last):
File "test_coattention_conf.py", line 276, in <module>
   &nbsp;&nbsp;&nbsp; main()
File "test_coattention_conf.py", line 165, in main
   &nbsp;&nbsp;&nbsp; for index, batch in enumerate(testloader):
File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
  &nbsp;&nbsp;&nbsp;  batch = self.collate_fn([self.dataset[i] for i in indices])
File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
&nbsp;&nbsp;&nbsp;    batch = self.collate_fn([self.dataset[i] for i in indices])
File "/home/ubuntu/COSNet/dataloaders/PairwiseImg_test.py", line 115, in __getitem__
&nbsp;&nbsp;&nbsp;    my_index = self.Index[seq_name1]
KeyError: 'bear'**

**Comment by Arnhav-Datar** [comment]
got the val_seqs.txt online, The program seems to be working

**Comment by Palaash05** [comment]
> got the val_seqs.txt online, The program seems to be working

Could you please share a link to that file, I am facing the same issue.
