### ISSUE TITLE
不能找到utils.colorize_mask和data.DataLoader

### ISSUE THREAD

**Issue by HuangLian126** [carrierlxk/COSNet#3]
您好！拜读了您的文章 See More, Know More: Unsupervised Video Object Segmentation with Co-Attention Siamese Networks，非常棒的无监督解决方案。我准备测试您的代码，十分遗憾无法跑通，缺少utils.colorize_mask和data.DataLoader。您可以上传相关的代码吗？万分感谢！！！

**Comment by carrierlxk** [comment]
你好， utils.colorize_mask可以屏蔽掉，另外一个是将test_coattention_conf.py第11行去掉屏蔽。我已经更新了test_coattention_conf.py这个函数。

**Comment by HuangLian126** [comment]
非常感谢能收到您的回复，我重新测试一下


 
---原始邮件---
发件人: "Lu Xiankai"<notifications@github.com&gt;
发送时间: 2019年9月12日(星期四) 下午2:30
收件人: "carrierlxk/COSNet"<COSNet@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"HuangLian126"<785105390@qq.com&gt;;
主题: Re: [carrierlxk/COSNet] 不能找到utils.colorize_mask和data.DataLoader (#3)



你好， utils.colorize_mask可以屏蔽掉，另外一个是将test_coattention_conf.py第11行去掉屏蔽。我已经更新了test_coattention_conf.py这个函数。

**Comment by gewenbin292** [comment]
还会提示5个错误，须将与davis无关的删掉，好像只提供了davis测试

**Comment by HuangLian126** [comment]
打扰了，遇到一个新问题。照着您的回复，删除与davis无关的东西之后，运行依然报错"PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason". 我用的pytorch1.2.0，上述问题是版本问题还是？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gewenbin292"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月12日(星期四) 下午2:51
收件人:&nbsp;"carrierlxk/COSNet"<COSNet@noreply.github.com&gt;;
抄送:&nbsp;"老黄"<785105390@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [carrierlxk/COSNet] 不能找到utils.colorize_mask和data.DataLoader (#3)




还会提示5个错误，须将与davis无关的删掉，好像只提供了davis测试

**Comment by carrierlxk** [comment]
应该是版本的问题，或者你直接用cpu跑吧

**Comment by shoutOutYangJie** [comment]
> 应该是版本的问题，或者你直接用cpu跑吧
looking forward to your training code .
