### ISSUE TITLE
训练阶段创建的saliency_data.txt问题

### ISSUE THREAD

**Issue by NoaHimesaka** [carrierlxk/COSNet#33]
readme里写到是用来store the saliency dataset name.
但是具体内容是什么？
saliency dataset 是用的MSRA10K 和DUTS
所以里面仅仅是写数据集的名称
也就是MSRA10K 和DUTS是吗？

**Comment by carrierlxk** [comment]
MSRA10K
DUTS_TE
DUTS_TR
DUT

**Comment by NoaHimesaka** [comment]
非常感谢！

**Comment by lih627** [comment]
> 非常感谢！

@NoaHimesaka 

Could you please tell me where to download  DUT dataset? I only find DUTS_TE and DUTS_TR.

Thanks a lot.

MSRA10K https://mmcheng.net/msra10k/
DUTS_TE http://saliencydetection.net/duts/
DUTS_TR http://saliencydetection.net/duts/
DUT

**Comment by NoaHimesaka** [comment]
> > 非常感谢！
> 
> @NoaHimesaka
> 
> Could you please tell me where to download DUT dataset? I only find DUTS_TE and DUTS_TR.
> 
> Thanks a lot.
> 
> MSRA10K https://mmcheng.net/msra10k/
> DUTS_TE http://saliencydetection.net/duts/
> DUTS_TR http://saliencydetection.net/duts/
> DUT

http://saliencydetection.net/dut-omron/
I use this.
But I'm not sure.
