### ISSUE TITLE
关于Jaccard index的计算问题

### ISSUE THREAD

**Issue by lscelory** [carrierlxk/COSNet#7]
您好，在拜读论文和代码后产生几个疑问，希望能得到解答！
1. 文中的测试指标J(Jaccard index/Region Similarity)是求分割结果和groundtruth mask的交并比，但是您的文中和代码中都表明最后的网络输出结果是一个单通道的灰度图，在每个坐标点输出的值为经过sigmoid之后的范围为0-1的值。那么这个输出结果是如何和groundtruth mask的{0,1}值计算J呢？是用一个阈值来截断么？
2. 观察到您的网络输入图像是由cv2读入，像素值范围为[0,255]，这和一般的将像素值归一化到[0,1]后再转为tensor不同，请问您是如何考虑的，这样做有什么优点么？
希望能得到您的回复，感谢！

**Comment by carrierlxk** [comment]
For the first question, we use CRF as the post-processing to obtain the binary output.
Second, we just follow the input type of deeplab v3. I think the input range is decided by the pre-trained backbone network.

**Comment by lscelory** [comment]
thx!!!
